<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaventas [
    <!ELEMENT listaventas (venta)+>
    <!ELEMENT venta (importe, comprador, vendedor, fecha?, codigo_factura)>
    <!ELEMENT importe (#PCDATA)>
    <!ELEMENT comprador (#PCDATA)>
    <!ELEMENT vendedor (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT codigo_factura (#PCDATA)>
   
]>
<listaventas>
<venta>

<importe>asdg</importe>
<comprador>aasdfas</comprador>
<vendedor>adfa</vendedor>
<fecha>asdfas</fecha>
<codigo_factura>asf</codigo_factura>
</venta>
</listaventas>